steps:
  - name: maven:3-jdk-8
  #- name:  'gcr.io/cloud-builders/mvn'
    volumes: 
    - name: 'vol1'
      path: '/persistant_volume'
    entrypoint: mvn
    args: ["test"]
    dir: 'employeedemo'
  - name: maven:3-jdk-8
    volumes: 
    - name: 'vol1'
      path: '/persistant_volume'
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
