steps:
  - name: maven:3-jdk-8
  #- name:  'gcr.io/cloud-builders/mvn'
    entrypoint: mvn
    args: ["test"]
    dir: /employeedemo
  - name: maven:3-jdk-8
    entrypoint: mvn
    args: ["package", "-Dmaven.test.skip=true"]
